library(shiny)
library(htmlwidgets)
library(timevis)
library(tidyverse)
library(RSQLite)
library(here)
library(lubridate)
library(plotly)
library(data.table)
library(vistime)
library(RColorBrewer)
library(webshot)
library(here)
library(shinydashboard)
library(pool)

pool<-dbPool(
  drv = RSQLite::SQLite(),
  dbname = paste0(here(),'/','equipment.db')
)
