---
title: "Marne Scince Equipment Bookings"
output:
  flexdashboard::flex_dashboard:
    orientation: rows
    code_folding: hide
---

```{r}
library(htmlwidgets)
library(timevis)
library(tidyverse)
library(RSQLite)
library(here)
library(lubridate)
library(plotly)
library(data.table)
library(vistime)
library(RColorBrewer)
library(webshot)
library(here)
library(highcharter)
```


```{r echo=FALSE, fig.show='hide', message=FALSE, warning=FALSE, paged.print=FALSE, results='hide'}
  con<-dbConnect(RSQLite::SQLite(),
    paste0(here(),'/','equipment.db'))

palette1 <- as.data.table(colorRampPalette(brewer.pal(8, "Dark2"))(12))
palette2<- as.data.table(colorRampPalette(brewer.pal(12, "Paired"))(18))
mycolors<-bind_rows(palette1,palette2) 
mycolors$user_id<-seq(1:nrow(mycolors))


  booking<-tbl(con,'tbl_booking') %>% as_data_frame()

  dept<-tbl(con,'tbl_dept')%>% as_data_frame()
  equipType<-tbl(con,'tbl_equipType')%>% as_data_frame()
  equip<-tbl(con,'tbl_equipment')%>% as_data_frame()
  instit<-tbl(con,'tbl_instit')%>% as_data_frame()
  user<-tbl(con,'tbl_user')%>% as_data_frame()
  equipAlloc<-tbl(con,'tbl_equipAllocation')%>% as_data_frame()

```


```{r echo=FALSE, fig.height=5, fig.width=5, message=FALSE, warning=FALSE, paged.print=FALSE}
data<- booking %>% 
  left_join(user,by='user_id') %>%
  left_join(equipAlloc, by = 'booking_id') %>%
  full_join(equip, by='equip_id') %>%
  left_join(equipType, by='type_id') %>% 
  as.data.table() %>%
  left_join(mycolors,by='user_id', copy=T) %>% 
  # mutate(start_date=dmy(start_date),
  # end_date=dmy(end_date)) #%>% 
  mutate(days=difftime(end_date,start_date)) %>%
  mutate(tooltips = paste("Booking ID: ",booking_id,"<br>",
                          "Start: ",start_date, "<br>",
                          "End: ",end_date, "<br>",
                          "User: ",fullName
                          )) %>% 
   #filter(!is.na(booking_id)) %>%
   #rename(start=start_date, end=end_date,group=equip_name, event=fullName,color=V1)%>%
  select(c('Booking ID' = booking_id,
           event=fullName,
           start=start_date,
           end = end_date,
           group = equip_name,
           color = V1,
           days, 
           tooltips,
           equip_order)) %>% 
   #select(c(8,11,4,5,10,16,14,15,12)) %>%
    arrange(equip_order) %>%
    hc_vistime(col.event="event",
           col.group="group",
           col.start="start",
           col.end="end",
           col.tooltip = "tooltips",
           col.color = "color",
           show_labels = F,
           linewidth = 20,
           title = "Marine Science Equipment Bookings")


data #%>%
  # layout(height=700,
  #   yaxis=list(fixedrange=TRUE,
  #              size = 50
  #              ),
  #   xaxis=list(
  #      rangeselector = list(
  #       buttons = list(
  #         list(
  #           count = 1,
  #           label = "1 mo",
  #           step = "month",
  #           stepmode = "backward"),
  #                   list(
  #           count = 3,
  #           label = "3 mo",
  #           step = "month",
  #           stepmode = "backward"),
  #                   list(
  #           count = 6,
  #           label = "6 mo",
  #           step = "month",
  #           stepmode = "backward"),
  #                   list(
  #           count = 12,
  #           label = "1 yr",
  #           step = "month",
  #           stepmode = "backward")
  #         ))
  #   )
  #   )
```